### ISSUE TITLE
It works perfectly. What about importing Illustrator in the same way. It would be very cool.

### ISSUE THREAD

**Issue by khaled-muhammad** [MiMillieuh/Photoshop-CC2021-Linux#16]
It works perfectly. What about importing Illustrator in the same way. It would be very cool.
There is one which is imported by @Gictorbit but it is very old. https://github.com/Gictorbit/illustratorCClinux

**Comment by MiMillieuh** [comment]
Well newer illustrator are really complicated to run.

It requires to maybe even patch wine and it's hard to do.

I'm focusing on PS2022 now maybe one day I'll try again to make illustrator working...

In the meantime the one you mentioned works perfectly and I use it.

Thanks for the suggestion.

**Comment by khaled-muhammad** [comment]
Wow PS 2022 that is soooo coool. You I tried a lot of ways until I found you on github. That is the most stable version until now (Also the most updated one)
I've a question... I am 14 years old. I learnt a lot of programming languages until that moment. What is the needed skills for porting windows app to work with Wine.

**Comment by khaled-muhammad** [comment]
That is my skills. Also, I think it is in another direction 
https://eng-khalid-portfolio.netlify.app/MySkills

**Comment by khaled-muhammad** [comment]
@MiMillieuh

**Comment by MiMillieuh** [comment]
> Wow PS 2022 that is soooo coool.  I tried a lot of ways until I found you on github. That is the most stable version until now (Also the most updated one)
> I've a question... I am 14 years old. I learnt a lot of programming languages until that moment. What is the needed skills for porting windows app to work with Wine?

I'll be a 100% fair with you....
It's just looking around... See on what the app depends on and what makes it crashes... It's not really porting but more like removing things that aren't working with wine... And testing... A lot of testing.

If you want you could try it's not that hard for simpler application.

Just keep an eye on the terminal when you launch an app ^^

**Comment by khaled-muhammad** [comment]
Oh, That is why you removed The home screen from PS. But, what programming languages do you use to do that? @MiMillieuh

**Comment by MiMillieuh** [comment]
Well I didn't removed it, it just doesn't appear because it can't... Or maybe I've removed something that it needs...

I don't use any programming language for this. It's really just a cat an mouse game ^^

But of course knowledge on a C like language is recommended

**Comment by khaled-muhammad** [comment]
Ok, 
`By a cat and mouse game I mean that you are the cat and you need to find the mouse that prevents the software to run...`
I mean technically
