### ISSUE TITLE
CameraRaw filter

### ISSUE THREAD

**Issue by Froztmuffins** [MiMillieuh/Photoshop-CC2021-Linux#2]
How to install Camera Raw filter

**Comment by MiMillieuh** [comment]
Hello, I don't really use camera raw... But I think it would be possible but I need to pack it it could be interesting , I'll try to update it so stay tuned 

Please keep this issue open so I'll remember if I forget.

**Comment by MiMillieuh** [comment]
Little update... 
So I have some bad news : Installing Camera Raw create a lot of bugs and Photoshop is "unusable" like it's impossible to create new files and some random error message pops up...

So I'm trying to fix it but don't know how much time it will take or even if I'll be able to do it...

**Comment by knminhaz** [comment]
> **GREAT NEWS GUYS !** I managed to get it working... Just need to package it Also just fix some issue because it's greyed out after a few moments... so not really usable but working at least (just need to check because I messed up with dependencies ) ![image](https://user-images.githubusercontent.com/52078885/139124504-b176ec8c-83d7-47fb-9f54-4b68380dddd4.png)

Wow wow wow! Hats off to you.

Please do pack the new script. Would love to use it and replace my current workflow.

I would like to promote this script. Do I have your permission?

**Comment by MiMillieuh** [comment]
> > **GREAT NEWS GUYS !** I managed to get it working... Just need to package it Also just fix some issue because it's greyed out after a few moments... so not really usable but working at least (just need to check because I messed up with dependencies ) ![image](https://user-images.githubusercontent.com/52078885/139124504-b176ec8c-83d7-47fb-9f54-4b68380dddd4.png)
> 
> Wow wow wow! Hats off to you.
> 
> Please do pack the new script. Would love to use it and replace my current workflow.
> 
> I would like to promote this script. Do I have your permission?

Well I was trying to avoid the user to do things... but I didn't managed to... so here a new version that require a little step before using camera raw : https://github.com/MiMillieuh/Photoshop-CC2021-Linux/releases/tag/1.1

I'll try to do it more cleanly but at least it's working without the grayed out issue if you follow the steps in the relase tag.

For those that aren't using camera raw just use the 1.0 as I haven't tried stability actually.

**Comment by Froztmuffins** [comment]
Thank you

**Comment by knminhaz** [comment]
> > > **GREAT NEWS GUYS !** I managed to get it working... Just need to package it Also just fix some issue because it's greyed out after a few moments... so not really usable but working at least (just need to check because I messed up with dependencies ) ![image](https://user-images.githubusercontent.com/52078885/139124504-b176ec8c-83d7-47fb-9f54-4b68380dddd4.png)
> > 
> > 
> > Wow wow wow! Hats off to you.
> > Please do pack the new script. Would love to use it and replace my current workflow.
> > I would like to promote this script. Do I have your permission?
> 
> Well I was trying to avoid the user to do things... but I didn't managed to... so here a new version that require a little step before using camera raw : https://github.com/MiMillieuh/Photoshop-CC2021-Linux/releases/tag/1.1
> 
> I'll try to do it more cleanly but at least it's working without the grayed out issue if you follow the steps in the relase tag.
> 
> For those that aren't using camera raw just use the 1.0 as I haven't tried stability actually.

It's working great now. No issues yet. Will be using it to test it further.

**Comment by MiMillieuh** [comment]
> > > > **GREAT NEWS GUYS !** I managed to get it working... Just need to package it Also just fix some issue because it's greyed out after a few moments... so not really usable but working at least (just need to check because I messed up with dependencies ) ![image](https://user-images.githubusercontent.com/52078885/139124504-b176ec8c-83d7-47fb-9f54-4b68380dddd4.png)
> > > 
> > > 
> > > Wow wow wow! Hats off to you.
> > > Please do pack the new script. Would love to use it and replace my current workflow.
> > > I would like to promote this script. Do I have your permission?
> > 
> > Well I was trying to avoid the user to do things... but I didn't managed to... so here a new version that require a little step before using camera raw : https://github.com/MiMillieuh/Photoshop-CC2021-Linux/releases/tag/1.1
> > 
> > I'll try to do it more cleanly but at least it's working without the grayed out issue if you follow the steps in the relase tag.
> > 
> > For those that aren't using camera raw just use the 1.0 as I haven't tried stability actually.
> 
> It's working great now. No issues yet. Will be using it to test it further.

Glad to hear ^^ if you have any other issues feel free to reopen or to open a new issue.
I'll try to help
