### ISSUE TITLE
not working pop os 22.10

### ISSUE THREAD

**Issue by MOBO-Timmy** [MiMillieuh/Photoshop-CC2021-Linux#7]

**Comment by MiMillieuh** [comment]
![Screenshot_20220207-065709_GitHub.png](https://user-images.githubusercontent.com/52078885/152732694-1cc804ea-9aa5-45b0-b9af-720840272ffc.png)

Maybe providing something to help finding the problem ?...

Like logs, your system configuration... If you get icon or not... Did you read readme... Cause the link is not working so you have to download the archive in the folder where you have installer.sh
