### ISSUE TITLE
PS wouldn't download from MediaFire

### ISSUE THREAD

**Issue by CHJ85** [MiMillieuh/Photoshop-CC2021-Linux#9]
Hi there. I ran the script, but it failed to download AdobePhotoshop2021.tar.xz from Mediafire.

**Comment by MiMillieuh** [comment]
Please read Readme... And download the file manually... I need to find a host that allows unlimited downloads...

Just past the file where your installer is located.

**Comment by MiMillieuh** [comment]
If it still fails install there was an update with tar I guess that extract now in folder instead of the contents a fix for this will came soon

**Comment by CHJ85** [comment]
Thank you. I thought perhaps Mediafire had some sort of a protection against scripts that auto download from their servers or something.
Btw. I tried the PR that somebody submitted.
You might wanna merge that one. It looks a bit more organized with the colors.
I've been using Photoshop 2021 for a minute now. Works great. Wine has come a long way.
